@startuml

class AverageDisplay{
  -sum:float
  -count:int
  display()
  update()
}

class MainDriver{
  main()
}

class NumericDisplay{
  -value:int
  display()
  update()
}

interface Observer{
  update()
}

interface Subject{
  attach()
  detach()
  notifyObservers()
}

class TemperatureSensor{
  -observers:ArrayList of Observer
  -tempState:int
  attach()
  detach()
  getTemp()
  notifyObservers()
  setTemp()
}

class TextDisplay{
  -value:int
  display()
  update()
}

Observer <|--- AverageDisplay

Observer <|--- NumericDisplay

TemperatureSensor ---> Observer

Subject <|--- TemperatureSensor

Observer <|--- TextDisplay

@enduml
